wp-cli/wp-cli-tests

features/steps/given.php
=> Add `Given a ... cache file` step

README.md, features/bootstrap/FeatureContext.php, features/steps/given.php
Situation:
I'm developing a WordPress plugin that registers some WP-CLI commands. Now I want to write some functional tests for these, ideally by leveraging this identical testing framework as for standalone commands.
In case anyone's wondering, the plugin I'm developing can be found at https://github.com/wearerequired/traduttore.
To run the tests, I need to activate / load the plugin somehow.
One suggestion by Daniel that led me to the right path was creating a ZIP archive and installing that ZIP file. He did this in a plugin once where `FeatureContext.php` was part of the code base. I obviously can't edit that file because it's now in the `wp-cli-tests` package.
Alain's suggestion was to use something like this:
```gherkin
Feature: Testing a custom plugin
Background:
Given a WP …
```
=> [WIP] Make it easier to write tests for WordPress plugins containing CLI commands

composer.json, phpcs.xml.dist
... which includes PHPCompatibility 9.0 and lots of new sniffs.
Refs:
* https://github.com/PHPCompatibility/PHPCompatibilityWP/releases/tag/2.0.0
* https://github.com/PHPCompatibility/PHPCompatibility/releases/tag/9.0.0
=> PHPCompatibilityWP: update to use version ^2

features/bootstrap/FeatureContext.php, tests/test-behat-tags.php, utils/behat-tags.php
* No multiple assignments in one statement.
* One space on the inside of open/close parenthesis when there is content between them.
* Use tabs for indentation, spaces for inline alignment.
* No precision alignment.
=> PHPCS: fix up the code base [1] - whitespace

features/bootstrap/Process.php, features/bootstrap/utils.php
* Always use parenthesis when instantiating a new object.
=> PHPCS: fix up the code base [2] - object instantiation

tests/test-behat-tags.php
* Always specify visibility for all class properties and methods.
=> PHPCS: fix up the code base [3] - scope modifiers

features/bootstrap/FeatureContext.php, features/bootstrap/support.php, features/bootstrap/utils.php, features/steps/then.php
* Use strict comparisons.
* Use the `$strict` parameter when calling `in_array()`.
=> PHPCS: fix up the code base [4] - strict comparisons

features/bootstrap/FeatureContext.php, features/bootstrap/utils.php, features/steps/given.php, features/steps/then.php, tests/bootstrap.php, utils/behat-tags.php
* Each argument in a multiline function call should start on a new line.
Note: in the (near?) future, multi-line arguments in function calls will also be  prohibited.
This will impact (some of) this code.
The choice for the future is:
* Either change the closures to full-blown methods.
* Declare them before the function call, assign them to a variable and pass the  variable to the function call.
=> PHPCS: fix up the code base [6] - multi-line function calls

features/bootstrap/utils.php
Variable names should be in `snake_case`.
As this is a function local variable, it can be safely renamed without BC.
=> PHPCS: fix up the code base [10] - rename a local variable

features/bootstrap/FeatureContext.php, tests/bootstrap.php
This removes the unprefixed variables from the global namespace to fix WPCS issues.
Related #44
=> Wrap Behat & PHPUnit bootstrapping code into a function

.distignore, .gitignore, .readme-partials/USING.md, WP_CLI_CS/ruleset.xml, bin/run-phpcs-tests, composer.json, features/bootstrap/support.php, features/extra/no-mail.php, phpcs.xml.dist, tests/bootstrap.php
A PHPCS standard is in principle the same as a custom ruleset with these differences:
Custom ruleset | External PHPCS standard
--- | ---
File: `[.]phpcs.xml[.dist]` | File: `ruleset.xml`
Can be included in other rulesets using the path to the file (which can get complicated) | Can be included in other rulesets by name
Can only use existing sniffs | Can add new sniffs native to the standard (not currently used)
Aside from that, one has to keep in mind that all paths used in a ruleset are interpreted _relative to the ruleset_.
As an external standard can be installed both globally as well as local to a project, it is better not to have any specifics involving file paths in an external standard, but to use a custom ruleset, which generally lives in the project root, for this instead.
So, …
=> Create a `WP_CLI_CS` standard for PHP_CodeSniffer

.travis.yml, WP_CLI_CS/ruleset.xml
This adds two checks:
1. Validation of the `WP_CLI_CS` ruleset against the PHPCS ruleset format as defined in the XSD file.
2. A check that the ruleset is formatted consistently, i.e. using tab indents, indented correctly, valid strict XML etc.
Both these checks need the `libxml2-utils` package to be available and both checks only need to be run once as the output will not change based on PHP versions.
As the `libxml2-utils` package is not a package which can be required via Composer, it did not make sense to add these commands as Composer scripts as, in that case, the `xmllint` package may not be available on the machine running the commands.
With that in mind and as these checks will only be needed for this repo and not for the project repos, I've added the necessary changes straight …
=> Travis: Add QA-checks for the WP_CLI_CS ruleset

phpcs.xml.dist
Showing the sniff name makes it easier to whitelist issues if needed.
=> Always show sniff name in addition to error message

features/bootstrap/FeatureContext.php
The ID comparison failed to detect parent/child relationships due to the strict check.
Related #46
=> Fix ID comparison

features/steps/given.php
Mac OS X puts some of the system folders like `/var` and `/tmp` into a special hidden `/private` folder. When checking whether the folder to delete is indeed within a temp folder (as a safeguard), we should also allow for a version of the temp folder prefixed with `/private`.
=> Allow for temp folder to be prefixed with `/private`

features/steps/given.php
When using Behat for creating a file, we should allow for variable substitution in the file path and the file contents as well.
=> Replace variables in generated file path and content

README.md, composer.json
If they are incldued as a regular dependency, their `dev-master` bleeds over to other packages and requires them to drop their `minimum-stability`.
=> Move roave security advisories to dev dependencies

.travis.yml, features/bootstrap/FeatureContext.php
This pull request ensures that column-statistics is not used if supported by the user's version of mysql.  If column-statistics are supported by the user's version of mysql supports column-statistics, the  `--skip-column-statistics` tag is added to the `mysqldump` command. 
This is related to #4, wp-cli/db-command#103, and wp-cli/db-command#105
=> Fix MySQL8 column-statistics compatibility issue

features/extra/polyfills.php
Add a polyfill for the is_customize_preview(), as it is required for the
TwentyTwenty theme's starter content, and will fatal the site if you install
WP 5.3 first (setting TwentyTwenty as the active theme) and then downgrade
to a version of WP lower than 4.0.
Note: This is a quick fix, and a cleaner solution would be to change the
active theme on downgrading, if the current theme declares it is not
supported.
See: https://github.com/WordPress/twentytwenty/issues/973
=> Add is_customize_preview() polyfill

composer.json
The DealerDirect Composer plugin has just released version `0.6.0`.
As Composer treats minors < 1.0 as majors, updating to this version requires an update to the `composer.json` requirements.
> For pre-1.0 versions it also acts with safety in mind and treats `^0.3` as `>=0.3.0 <0.4.0`.
Note: As underlying standards may not have updated their requirements for this plugin yet, I've kept the requirement flexible so as to prevent conflicts.
Refs:
* https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.6.0
* https://getcomposer.org/doc/articles/versions.md#caret-version-range-
=> Update PHPCS Composer plugin dependency

README.md, bin/install-package-tests
The way the password was forwarded meant it just hangs `mysql` on an empty password.
=> Fix password variable

.travis.yml, bin/install-package-tests, composer.json
Database credentials for `composer prepare-tests` can now be provided via the same environment variables that `composer behat` accepts:
- `WP_CLI_TEST_DBHOST` is the host to use and can include a port, i.e `127.0.0.1:33060` (defaults to `localhost`)
- `WP_CLI_TEST_DBUSER` is the user that has permission to administer databases and users (defaults to `root`).
- `WP_CLI_TEST_DBPASS` is the password to use for the above user (defaults to an empty password).
=> Reuse Behat `WP_CLI_TEST_*` constants for `prepare-tests` script

features/bootstrap/FeatureContext.php
To allow for reliable testing commands that create a config file on demand, we need to remove any existing global config file after each scenario.
=> Delete global config after scenarios

features/bootstrap/FeatureContext.php
These can be used within Behat tests to construct config files or similar, where the exact settings of the current DB connection are needed.
=> Add DB settings as individual variables

features/bootstrap/FeatureContext.php
The `vendor` folder was not correctly discovered, but rather we returned the `bin` folder instead. Also, the prioritization of which `vendor` folder to use was adapted as well.
=> Rectify vendor folder discovery

.travis.yml, features/bootstrap/support.php, features/steps/then.php
This PR adds the possibility to negate the following rules by adding a `not`:
* `/^the contents of the (.+) file should( not)? match (((\/.+\/)|(#.+#))([a-z]+)?)$/`
* `/^(STDOUT|STDERR) should( not)? match (((\/.+\/)|(#.+#))([a-z]+)?)$/`
=> Allow negated match for both file contents and `STDOUT|STDERR` checks

composer.json
This PR:
- ensures a Behat minimum of v2.5.5
- raises the minimum PHP version to v5.6
- sets the PHP platform requirement to v5.6
=> Update dependency requirements

features/bootstrap/FeatureContext.php
This is needed to avoid permission errors starting with MySQL 5.7.31.
See https://github.com/wp-cli/db-command/issues/180
=> Use --no-tablespaces by default for mysqldump

.github/workflows/code-quality.yml, .github/workflows/testing.yml, bin/install-package-tests
Instead of hardcoding the SQL statements to prepare the DB into the GHA workflow, reuse `composer prepare-tests` instead.
=> Use `composer prepare-tests` in GHA workflows

src/Context/FeatureContext.php
This adds `DB_ROOT_USER` & `DB_ROOT_PASSWORD` to the array of variables that can be used within Behat tests for substituion.
=> Add DB root user & pass to Behat vars

bin/install-package-tests
This PR adds support for MariaDB to the `composer prepare-tests` command.
The entire script should be POSIX-compliant, so hopefully platform support is good now.
=> Add support for MariaDB

src/Context/FeatureContext.php
If the environment does not contain environment variables to set the DB credentials, Behat should ensure it doesn't try to access undefined variables and rather make a best guess instead.
These are the fallback being used:
```
DB_USER     => wp_cli_test
DB_PASSWORD => password1
DB_HOST     => localhost
```
=> Handle missing DB credentials gracefully

utils/no-mail.php
This PR updates the bundled test implementation of `wp_mail` to work slightly closer to the real implementation.
Most importantly, it returns `true` to indicate mail was successfully sent (this is how the function worked before as well). It also supports a potential array of recipients, as supported by the core function to avoid a potential array-to-string conversion error in the event an array is passed.
=> Update test `wp_mail`

README.md
Pretty self-explanatory change – the current example isn't valid (at least with v3 of Behat). Essentially copied from [the current `behat.yml`](https://github.com/wp-cli/wp-cli-tests/blob/03fdabdae9e9a081ef57b0ce7e6d66dc45212c09/behat.yml).
=> Update behat.yml in setup instructions

src/Context/ThenStepDefinitions.php
Updates Behat then step definition for checking whether a given file or folder exists or not to fix an edge case where it could report inaccurate results due to PHP's internal cache for filesystem metadata.
It also changes the name of the test function to be more expressive as the "test" is specific to existence, so it makes sense to name it accordingly 🙂 
Here's a POC script showing the problem in general. From my testing, `is_dir` is perhaps the only problem here, although [docs mention `file_exists` (among many others)](https://www.php.net/manual/en/function.clearstatcache.php), although I wasn't able to reproduce the same with `file_exists` (as shown below) so perhaps it's a bit better than it used to be on newer versions of PHP 🤷‍♂️ 
```php
$to_str = fn( $data ) => var_export( $data, …
```
=> Update file/folder existence check for cache safety

.github/workflows/testing.yml, .readme-partials/USING.md, bin/install-package-tests, src/Context/FeatureContext.php
This adds `WP_CLI_TEST_DBNAME` as a new supported environment variable and `$DB_NAME` as a new runtime Behat variable.
=> Add DB name as env variable and runtime variable

src/Context/Support.php
When comparing two strings, this PR strips the contained ANSI color codes, as these should not be a factor in whether the strings match.
=> Strip ANSI colors on string comparison

src/Context/Support.php, src/Context/ThenStepDefinitions.php
As a follow-up to #130, this PR adds an optional strict mode to string comparison in case the actual ANSI codes need to be checked.
=> Add strict mode to string comparisons

src/Context/ThenStepDefinitions.php
Adds `strictly` to file comparisons to be coherent with string comparisons.
=> Add strict mode to string comparisons for files

composer.json
See details here -> https://github.com/Roave/SecurityAdvisories#stability
=> Use latest branch for Roave security advisories

src/Context/FeatureContext.php
The test setup apparently does not include the `WP_CLI_ALLOW_ROOT` variable into the `wp cli` process that would cause some commands to fail when initialising the test.
```bash
root@3d05a502038c:/var/www/workspace/packages/composer/wp-cli# composer behat
> run-behat-tests
---
--- Failed hooks:
BeforeSuite # WP_CLI\Tests\Context\FeatureContext::prepare()
│ 
│ OS:     Linux 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64
│ Shell:
│ PHP binary:     /usr/local/bin/php
│ PHP version:    7.4.25
│ php.ini used:   /usr/local/etc/php/php.ini
│ MySQL binary:   /usr/bin/mysql
│ MySQL version:  mysql  Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
│ SQL modes:
│ WP-CLI root dir:        /var/www/workspace/packages/composer/wp-cli/vendor/wp-cli/wp-cli …
```
=> Include `WP_CLI_ALLOW_ROOT` in process env variables

bin/rerun-behat-tests, bin/run-behat-tests
This PR:
1. Changes the check for bailing early on Behat execution from the `features/` directory to the `behat.yml` file. Fixes #126 .
2. Changes `--rerun` usage to take changes from Behat v2 to Behat v3 into consideration.
3. Makes `rerun-behat-tests` reuse `run-behat-tests`, to avoid duplicating all of the logix.
=> Improve Behat binaries

composer.json, tests/test-behat-tags.php
Add support for PHP 8.1, by:
- Actually using PHPUnit Polyfills in the testcase
- Updating dependencies
- Making use of latest `wp-cli` which includes a fix for `mysqli` error reporting default mode change (See https://github.com/wp-cli/wp-cli/pull/5582)
=> Support PHP 8.1

src/Context/FeatureContext.php
When installing current WP-CLI framework from the Composer `path` repository, use a version alias to make the `dev-master` version meet the version constraints for tagged releases.
=> Use alias to make `dev-master` work as release

src/Context/FeatureContext.php
This PR adds `--no-interaction` centrally to ensure it is always use in feature files when running Composer commands.
This fixes issues where the Behat tests just hang when executed in an interactive shell but work correctly in GHA.
This PR also allows for all Composer plugins to run within the constructed test repository.
=> Ensure `--no-interaction` is used for all Composer commands

src/Context/FeatureContext.php
This may overcome the wp-cli/wp-cli CI errors.
https://github.com/Lewiscowles1986/wp-cli-tests/pull/5 shows it as green (although these don't seem to be gated in the same way wp-cli is)
=> Allow all plugins before requiring plugins 😉

src/Context/FeatureContext.php
When adding a `path` repository without explicit version information, Composer has switched to using `main` as the default development branch, instead of `master`. As `wp-cli/wp-cli` is still using `master` as the default branch, we need to be explicit about this.
=> Add explicit default branch for local `wp-cli` package

phpunit.xml.dist, tests/test-behat-tags.php, utils/behat-tags.php
There's one more failing test on https://github.com/wp-cli/extension-command/pull/347 that's specific to trunk: https://core.trac.wordpress.org/ticket/54504#comment:117
Rather than mark the entire test as failed, I want to only mark it failed for `WP_VERSION=trunk` and `WP_VERSION=nightly`.
=> Add ability to mark tests as broken on `trunk` and `nightly`

composer.json
=> Allow `wordpress-core-installer` in `composer.json`

.readme-partials/USING.md, README.md
From https://github.com/wp-cli/wp-cli-tests/pull/161
=> Add `phpcbf` mention to README

src/Context/FeatureContext.php
This fixes the following warnings I saw:
` 8192: Creation of dynamic property WP_CLI\Tests\Context\FeatureContext::$result is deprecated in /wp-cli-tests/src/Context/WhenStepDefinitions.php line 39`
`8192: Creation of dynamic property WP_CLI\Tests\Context\FeatureContext::$email_sends is deprecated in /wp-cli-dev/wp-cli-tests/src/Context/WhenStepDefinitions.php line 40
`
Which cause some behat tests to fail under PHP 8.2
All of the other variables in this class a very well commented, so this needs some input from anybody who has a good description of these two.
=> Fix PHP 8.2 deprication warnings

bin/run-behat-tests
Before:
```
$ composer behat -- --help
> run-behat-tests '--help'
Unsupported format "progress".
help [--format FORMAT] [--raw] [--] [<command_name>]
Script run-behat-tests handling the behat event returned with error code 1
```
Related https://github.com/wp-cli/handbook/pull/440
=> Avoid error when using `composer behat -- --help`

src/Context/FeatureContext.php
The `FeatureContext::$result` and `FeatureContext::$email_sends` properties were defined with private visibility as part of #165, which is now preventing the child class from using them in the event that more step definitions are added.
This PR seeks to restore the previous functionality, in which the child class was permitted access to the properties listed above.
=> Update `FeatureContext::$result` and `FeatureContext::$email_sends` visibility

src/Context/FeatureContext.php
This PR replaces one direct use of the `Requests` library with the `Utils\http_request()` helper to get around version compat issues.
=> Use http_request() helper instead of Requests directly

WP_CLI_CS/ruleset.xml
This PR updates the custom PHPCS ruleset to exclude all current filesystem functions to the list of exclusions.
=> Add missing filesystem function exclsuions

WP_CLI_CS/ruleset.xml
See https://github.com/wp-cli/wp-cli-tests/issues/175
=> Update PHPCS config

src/Context/FeatureContext.php
When the Behat context setup tried to find the `vendor` folder, it did not look into the current working folder first, instead always finding the `vendor` folder within the tests dependency instead.
This PR adapts the logic so that the current working directory gets searched first.
As an example, when running `composer behat` from within the `wp-cli-dev/config-command` folder, this  is the resulting change:
**BEFORE**
```
Vendor folder location: /home/alain/dev/wp-cli-dev/wp-cli-tests/vendor
Framework folder location: /home/alain/dev/wp-cli-dev/wp-cli-tests/vendor/wp-cli/wp-cli
WP-CLI binary path: /home/alain/dev/wp-cli-dev/wp-cli-tests/vendor/bin
```
**AFTER**
```
Vendor folder location: /home/alain/dev/wp-cli-dev/config-command/vendor
Framework folder location: …
```
=> Look into `getcwd()` first when searching for vendor folder

README.md, src/Context/FeatureContext.php, tests/test-behat-tags.php, utils/behat-tags.php
PR #181 added logic to detect an environment variable named `DB_TYPE` that allows to switch the database engine used for Behat testing from MySQL to SQLite.
This PR renames the environment variable `DB_TYPE` to `WP_CLI_TEST_DBTYPE`, because:
- `DB_TYPE` is a generic environment variable that is actively used in many other systems, and this could lead to weird behavior where unrelated projects like a JS+MongoDB app being developed on the same machine directly impact local testing for WP-CLI.
- all other configurable WP-CLI test database settings are available via `WP_CLI_TEST_DB*` environment variables to configure Behat.
=> Rename DB_TYPE env variable into WP_CLI_TEST_DBTYPE

features/testing.feature, src/Context/FeatureContext.php
`wp config create` by default checks the database connection when trying to create the `wp-config.php` file, and uses `die()`when the connection fails. This happens on CI because there is no MySQL server running.
https://github.com/wp-cli/config-command/blob/ca25b73e798657ac1846c99b96d3ae8d22be4f34/src/Config_Command.php#L159-L171
=> SQLite: fix `wp-config.php` creation

features/testing.feature, src/Context/FeatureContext.php
Adds a test in this repo so we don’t have to find out by looking at other repos
Note:
I accidentally found out that the following doesn't work:
```
Given a WP install with Composer
And a custom wp-content directory
```
That's because of a different `RUN_DIR`, but this scenario is never tested and probably doesn't need to be. And it's not isolated to SQLite either so would warrant its own PR.
Related https://github.com/wp-cli/wp-cli/issues/5859
=> Fix SQLite mu-plugins usage with composer installs

bin/install-package-tests
This PR adds parsing support for sockets in `composer prepare-tests`.
=> Support sockets in `composer prepare-tests`

bin/install-package-tests, src/Context/FeatureContext.php
Version 2.1.4 of the SQLite plugin contains a syntax error on PHP < 7.3. This PR locks the plugin version to 2.1.3 for now to make tests pass.
See https://github.com/WordPress/sqlite-database-integration/pull/62
=> Lock version of SQLite plugin to v2.1.3

utils/mapped_socket_folder/README.md
To be able to run tests against multiple DB versions for https://github.com/wp-cli/config-command/pull/171, we need a way of mounting a socket file within a MySQL Docker container into the surrouding host system.
This PR adds a folder that will always exist so that a bind mount can be established to mount the folder containing the socket file (the socket file cannot be mounted directly).
=> Add mapped_socket_folder to allow for socket-based DB testing

src/Context/FeatureContext.php, utils/mapped_socket_folder/README.md
This PR looks for the `WP_CLI_TEST_DBSOCKET` environment variables and maps it to the internal Behat variable `DB_SOCKET` so it can be used from within tests.
=> Add socket env to internal variables

src/Context/FeatureContext.php
See https://github.com/wp-cli/automated-tests/actions/runs/7287895211/job/19859462619#step:14:203
=> Avoid PHP warnings on missing variables

.editorconfig, .github/workflows/wp-versions-data-fetcher.yml
Add workflow to do the following tasks:
- Fetch data from `https://api.wordpress.org/core/stable-check/1.0/` and save it to `wp-versions.json` file.
- Create pull request against the `artifacts` branch in case no active pull requests are present.
- Push changes to the existing PR in case the PR exists.
Partially addresses https://github.com/wp-cli/wp-cli-tests/issues/51
Related: https://github.com/wp-cli/wp-cli/issues/5935
- Create a new orphan branch called `artifacts`.
- Commit empty `wp-versions.json` file and push to the `artifacts` branch. 
- Add required branch protection rules to avoid branch deletion by some automation or person.
- Enable `Allow GitHub Actions to create and approve pull requests` in `Settings > Actions > General`.
=> Add `wp-versions-data-fetcher` workflow

src/Context/FeatureContext.php
This PR updates the version of SQLite that is used during the tests. The current version is outdated and is missing various updates and fixes.
[Work that is done on the db command](https://github.com/wp-cli/db-command/pull/259) depends on a later version of the SQLite integration plugin.
=> Update the version of the SQLite plugin

src/Context/FeatureContext.php
In this PR we go back to using the latest version of the SQlite database integration plugin to ensure we always run the most up to date version.
This was discussed in #214
=> Use the latest SQLite version instead of locking it to a specific one

composer.json
As noted in #217 there hasn't been a release of [phpcompatibility](https://github.com/PHPCompatibility/PHPCompatibility/) since 2019 and the current version can't detect PHP 8 specific code. It probably has other useful fixes for earlier versions of PHP that have been applied in the last several years as well.
Fixes #217
=> Bump phpcompatibility requirement to development branch

bin/run-php-unit-tests
Display warnings/notices/deprecations on PHPUnit 10+ and fail on them as well.
=> Add extra arguments to PHPUnit 10+

bin/install-package-tests
Bug Ticket: https://github.com/wp-cli/ideas/issues/194
This PR should fix the `composer prepare-tests` command issue on the [wp-cli-dev](https://github.com/wp-cli/wp-cli-dev) repo existing for anyone running sql version 8.0.4+
=> Tests: Replace `mysql_native_password` with `caching_sha2_password`

tests/bootstrap.php
The current regex doesn't work if all the attributes in the PHPUnit config file are on one line.
=> PHPUnit: Fix regex in bootstrap file

src/Context/Support.php
Addresses the following test failure on PHP 8.4: https://github.com/wp-cli/wp-cli/actions/runs/11656752489/job/32453448665#step:11:76
```
str_getcsv(): the $escape parameter must be provided as its default value will change in vendor/wp-cli/wp-cli-tests/src/Context/Support.php line 175
```
As per the [documentation](https://www.php.net/manual/en/function.str-getcsv.php):
> Warning
When escape is set to anything other than an empty string ("") it can result in CSV that is not compliant with [» RFC 4180](http://www.faqs.org/rfcs/rfc4180) or unable to survive a roundtrip through the PHP CSV functions. The default for escape is "\\" so it is recommended to set it to the empty string explicitly. The default value will change in a future version of PHP, no earlier than PHP 9.0.
=> Explicitly provide `$escape` to `str_getcsv`

src/Context/ThenStepDefinitions.php
This unblocks https://github.com/wp-cli/core-command/pull/277 where I intend to use a saved variable in a regex
=> Replace variables in regexes

.gitignore, phpunit.xml.dist
Fixes a currently failing code coverage job because the PHPUnit config is outdated.
See https://github.com/wp-cli/wp-cli/issues/6035
See #234
=> Allow collecting PHPUnit coverage

features/http-mocking.feature, src/Context/GivenStepDefinitions.php
The expected output changed because there are new table columns. Figured just changing it to CSV output makes the test more stable.
Also fixes HTTP mocking for WordPress 4.9, which uses Requests v1.
=> Fix HTTP mocking test / Requests v1 support

src/Context/FeatureContext.php, utils/generate-coverage.php
See #241
To test:
1. Check out the `wp-cli/wp-cli` repo
2. Run `composer install`
3. Copy the changes in this file to `vendor/wp-cli/wp-cli-tests/utils/generate-coverage.php`
4. Run `WP_CLI_TEST_COVERAGE=1 composer behat features/aliases.feature:3`
=> Fix code coverage for main framework repo

src/Context/FeatureContext.php, utils/generate-coverage.php
See #241 and specifically https://github.com/wp-cli/wp-cli-tests/issues/241#issuecomment-2745192224
In a nutshell:
* Do not collect coverage if the command is executed as part of the tests setup, e.g. when downloading core or getting `wp cli info` in `FeatureContext`.
* Update coverage file name so that a new file is created for each individual step.
* Save coverage files as serialized classes so that they can be merged together later
* In `FeatureContext`, after finishing the test suite, merge all coverage files together into a single XML file
This requires passing the `--xdebug` flag to Behat so that it's available there. Otherwise we can't instantiate a new `CodeCoverage` class. See https://github.com/wp-cli/.github/pull/124 for adding this change in our CI.
=> Create multiple coverage files and merge them all together

bin/install-package-tests, composer.json, features/steps.feature, src/Context/FeatureContext.php, tests/tests/TestBehatTags.php, utils/behat-tags.php
To-do: correctly set `WP_CLI_TEST_DBTYPE=mariadb` in https://github.com/wp-cli/.github
=> Improve MariaDB detection

src/Context/FeatureContext.php
This is related to the remaining failing Behat tests when code coverage is running.
Basically what happens in the wp-cli-bundle repo is that we include the autoloader once in `generate-coverage.php`, and then in the generated Phar the same autoloader is included again. That causes a fatal error because the same `ComposerAutoloaderInit...` class is declared twice.
This PR addresses this by temporarily changing the autoloader class suffix for that generated Phar. Requires otherwise using a hardcoded suffix (instead of the default `content-hash`). See https://github.com/wp-cli/wp-cli-bundle/pull/764 for that.
Requires the PHP 7.2 bump, see https://github.com/wp-cli/wp-cli-bundle/pull/760
See [Slack discussion](https://wordpress.slack.com/archives/C02RP4T41/p1746635308451319) for additional …
=> Dump a new autoloader when generating a Phar

.gitignore, composer.json, phpunit.xml.dist, tests/tests/TestBehatTags.php
=> Use PHPUnit Polyfills v4

composer.json, extension.neon, phpcs.xml.dist, phpstan.neon.dist, src/Context/FeatureContext.php, src/Context/GivenStepDefinitions.php, src/Context/ThenStepDefinitions.php, src/PHPStan/GetFlagValueFunctionDynamicReturnTypeExtension.php, src/PHPStan/ParseUrlFunctionDynamicReturnTypeExtension.php, src/PHPStan/WPCliRuncommandDynamicReturnTypeExtension.php, tests/data/get_flag_value.php, tests/data/parse_url.php, tests/data/runcommand.php, tests/tests/PHPStan/TestDynamicReturnTypeExtension.php, tests/tests/TestBehatTags.php
See #203
Admittedly, the custom PHPStan extensions are AI-generated, so might need some clean up. But hey, they work!
=> PHPStan enhancements
