- features/steps/given.php
This fixes #6 and resolves the problem I had with https://github.com/wp-cli/language-command/pull/38.
> Use realpath() when comparing paths

- bin/run-php-unit-tests
- bin/run-phpcs-tests
- tests/bootstrap.php
> Run both PHPUnit bootstrap files

- .travis.yml
- README.md
> Explain how to re-run failed scenarios

- tests/bootstrap.php
> Fix fetching the VERSION file from the framework

- tests/bootstrap.php
> Remove erroneous define from PHPUnit bootstrap

- .readme-partials/USING.md
I seem to have made changes directly to the `README.md` file, instead of to the partial that generates it.
This PR brings the partial back in line.
> Adapt the README.md partial

- features/bootstrap/FeatureContext.php
- features/bootstrap/support.php
> PHPCS: fix up the code base [5] - yoda conditions

- features/bootstrap/FeatureContext.php
* No assignments in conditions.
> PHPCS: fix up the code base [9] - assignments in conditions

- features/bootstrap/FeatureContext.php
- features/bootstrap/utils.php
* No assignments in conditions.
> PHPCS: fix up the code base [8] - assignments in conditions

- features/steps/then.php
> Use strict comparisons

- features/bootstrap/support.php
- features/steps/then.php
> Adapt variable names to move from camelCase to snake_case

- features/steps/when.php
> Prefix functions in global namespace

- features/bootstrap/FeatureContext.php
Solves https://travis-ci.org/wp-cli/entity-command/jobs/531936239#L751-L752
> Only create mu-plugins dir if it doesn't exist

- README.md
- features/bootstrap/FeatureContext.php
- features/bootstrap/support.php
- features/steps/given.php
- features/steps/then.php
- utils/behat-tags.php
> Fix typos and docs standards

- composer.json
Broadens the PHPUnit version constraints and adds the Yoast PHPUnit
polyfills.
> Improve PHPUnit integration

- .github/workflows/testing.yml
- src/Context/FeatureContext.php
> Show Behat environment debugging info

- src/Context/FeatureContext.php
This should add two variables for MySQL, which I believe will help in tests.
> add MYSQL_HOST and MYSQL_TCP_PORT

- src/Context/FeatureContext.php
From https://wordpress.slack.com/archives/C02RP4T41/p1665070169355629
> Always run WP core caching process, and display `wp core version`

- bin/run-phpcbf-cleanup
- composer.json
See https://github.com/wp-cli/.github/issues/41
> Add a `composer phpcbf` command

- bin/install-package-tests
See https://github.com/wp-cli/wp-cli-tests/issues/160
> Update install-package-tests to wait until MySQL is ready to accept connections

- bin/install-package-tests
From https://github.com/wp-cli/wp-cli-tests/pull/167
See https://github.com/wp-cli/wp-cli-tests/issues/160
> Use POSIX-compatible counter incrementing

- bin/install-package-tests
> Use host when checking MySQL server

- src/Context/FeatureContext.php
Fixes https://github.com/wp-cli/wp-cli-tests/issues/182
> In `copy_dir()`, use `cp -R` on Mac, `cp -r` everywhere else

- .readme-partials/USING.md
We need to update the partials instead of `README.md`.
Supersedes #185
> Fix readme

- src/Context/FeatureContext.php
- src/Context/GivenStepDefinitions.php
Related: https://github.com/wp-cli/wp-cli/issues/5859
> Move SQLite plugin to mu-plugins

- src/Context/FeatureContext.php
> Use existing `WpOrgApi` helper class

- src/Context/GivenStepDefinitions.php
- src/Context/ThenStepDefinitions.php
- src/Context/WhenStepDefinitions.php
> Add PHPDoc for Behat steps
